import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/client";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Defines the root layout for the application, applying global providers, font styles, and toast notifications.
 *
 * Wraps all pages with the tRPC provider, sets up the Inter font, and includes a global toast notification system.
 *
 * @param children - The content to be rendered within the layout
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
    <html lang="en">
      <body
        className={`${inter.className}  antialiased`}
      >
        <Toaster/>
        {children}
      </body>
    </html>
    </TRPCReactProvider>
  );
}
